In [155]:
# !pip install processor

In [156]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from processor.text import TextProcessor

### Read and overview data

In [157]:
data_dict = {'/content/drive/MyDrive/Data/L012/L12_V001-Scene-004-02-17160.jpg': ['HTV.',
  '18:30:13.',
  'Ảnh: VIỆT NAM, QUANG VINH, MUỐN NAM.',
  'TP.HCM: RA QUÂN HUẤN LUYỆN NĂM 2024.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-008-02-22280.jpg': ['ITIV.',
  'HD.',
  '1830:18.',
  'HAT.',
  '"Xét XỬỤ CỤ CÂM PHẠM ĐỜI TƯ..',
  'Bà Nguyễn Phương Hằng.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-016-02-32240.jpg': ['18:30:28.',
  'TAI NẠN LIÊN HOÀN TRÊN CAO TỐC VĨNH HẢO - PHAN THẾT.',
  'KHIẾN MỘT TÀI XẾT TỬ VONG.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-010-02-24760.jpg': ['HD.',
  '18:30:20.',
  'THÍNH.',
  'giây.',
  '"Xét XỬ VU "(XÂM PHẠM ĐỜI TƯ").',
  'Bà Nguyễn Phương Hằng.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-026-02-65960.jpg': ['VHD.',
  '18:31:01.',
  'TP.HCM: RA QUÂN HUẤN LUYỆN NĂM 2024.',
  'giây.',
  '69.',
  'Hơn 1.400 phụ nữ Bắc Kạn đồng diễn áo dài chào mừng 8/3.',
  '69.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-029-02-72400.jpg': ['HTV.',
  'HD.',
  '18:31:08.',
  'Bộ TƯ LỆNH.',
  'THÀNH PHỐ HỌ CHÍ MINH.',
  'REAUTINAMICATIVE.',
  'Caronhau choa chinh noavoavinducau Juamawn.',
  'áo dài chào mừng 8/3.',
  '60.',
  'Ngày Quốc tế Phụ nữ 8/3: 120 hoạt động đồng hành cùng phụ nữ.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-038-02-85040.jpg': ['HTV.',
  '183127.',
  '15 TP.HCM kiến nghị bác sĩ mới tốt nghiệp thực hành 12 tháng ở bệnh viện, 6 tháng lại trại.',
  '60.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-082-02-191680.jpg': ['HIV.',
  'HD.',
  '18:33:07.',
  'Interlines.',
  'UNINTS.',
  'H.',
  'swam.',
  '60.',
  'Tiền Giang: Giải cứu an toàn các bé bị gia cầm.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-098-02-249520.jpg': ['THỂ THAO.',
  'NỘI DUNG THÔNG TIN BÁO CHÍ.',
  '18:34:05.',
  'Qua năm, thông tin phản ánh trên báo chí về việc một số cụm rạp phổ biến phim.',
  '"Mai"), khâu kiếm soát vé khá lỏng lẻo, để lọt vào nhiều khán giả dưới 18 tuổi mua vé.',
  'Xem phim; ngày 21 tháng 02 năm 2024, Thanh tra Bộ Văn hóa, Thể thao và Du lịch có.',
  'Công văn số 14/TT-VHGĐ gửi Thanh tra các Sở Văn hóa, Thể thao và Du lịch; Sở.',
  'Văn hóa và Thể thao về việc tăng cường thanh tra, kiểm tra việc chấp hành quy định.',
  'pháp luật về điện ảnh tại rạp chiếu phim;',
  'Thực hiện chi đạo của Thanh tra Bộ, Thanh tra Sở Văn hóa và Thể thao có Công.',
  'Văn số 39/TTS ngày 21 tháng 02 năm 2024 về tăng cường kiểm tra xử lý hành vi vi.',
  'Vi phạm quy định pháp luật về phổ biến phim trên địa bàn Thành phố Hồ Chí Minh gửi.',
  'Phòng Văn hóa và Thông tin thành phố Thủ Đức và 21 quận, huyện theo đó đề nghị.',
  'Phòng Văn hóa và Thông tin thành phố Thủ Đức và 21 quận, huyện phối hợp với các.',
  'Tổ chức, cá nhân hoạt động kinh doanh lĩnh vực điện ảnh, cơ sở hoạt động kinh doanh,.',
  'Phỏ biến nhiều.',
  'Vi phạm nồng độ cồn lái xe máy gây tai nạn chết người.',
  '%.',
  'Đồng Tháp: Chìm ghe chở đất, một.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-103-01-258480.jpg': ['trong ảnh hưởng đến.',
  '"CNG TRANG THỊ THUNG TH THONH THỊT T. T. THỊ THUÔNH C TỔNG CÔNG.',
  'Nguyễn văn mạng với mộng và đâm khuỷ trong trong tra đa nội dung.',
  '18:34:14.',
  'PHƯỜI THỊ TH N. NG. T. Ngiangi trong cho cho chon chon giong tượng thuy.',
  'M.',
  'việc x.',
  'ht.',
  'Tha.',
  'Trười thời trong người, có vào.',
  'Phá.',
  'PHIỂN THẤN Ba T.. C,, CHồng C,...... """,.',
  'Từ khi.',
  '0380000000100.',
  '031000000001.',
  'Phim.',
  'không riêng TP.HCM.',
  'Chèi.',
  '038000000001.',
  '0000100001002.',
  'Số lượng xuôi.',
  'Tiêu để bã.',
  'Tóm tắt bà.',
  'Nội dung bài.',
  '60.',
  'Rù nhau đi bắt ốc, 2 thanh niên ở Bình Phước bị đuối nước.',
  '03/01/2024.',
  '452 Anh 1',
  'Phiên thị.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-170-02-480400.jpg': ['1837:56.',
  'Thủ tướng Haiti cam kết tổ chức tổng tuyển cử vào năm 200m.',
  'sớm có giải pháp chính trị cho Haiti.',
  '60.'],
 '/content/drive/MyDrive/Data/L012/L12_V001-Scene-169-02-477880.jpg': ['18:37:53.',
  'DEM 912875.',
  'Angless.',
  'Thủ tướng Haiti cam kết tổ chức.',
  '4.',
  'Liên Hiệp quốc kêu gọi sớm có giải pháp chính trị cho Haiti.'],
 '/content/drive/MyDrive/Data/L012/L12_V019-Scene-169-03-478840.jpg': ['18:38:51.',
  'Peter No.',
  'Trong tranh cử tại Nevada, Tổng thống Mỹ Biden nhấn mạnh kế hoạch giảm chi phí nhà ở thính.'],
 '/content/drive/MyDrive/Data/L012/L12_V019-Scene-232-01-695360.jpg': ['18:42:28.',
  'thác hải sản trái phép.',
  '69.',
  'TP.HCM kiến nghị Bộ TTTT quản lý, giải quyết nạn sử dụng sim rác lừ.'],
 '/content/drive/MyDrive/Data/L012/L12_V019-Scene-334-01-1012000.jpg': ['18:50:50.',
  'Nổ mỏ than ở Pakistan, 12 thợ mỏ thiệt mạng.',
  '69.',
  '60.',
  'Nhiều bệnh viện ở Trung Quốc.'],
 '/content/drive/MyDrive/Data/L012/L12_V019-Scene-358-03-1124280.jpg': ['HTV.',
  'HD.',
  '1856:34.',
  'Thibaut Courtois (Real Madrid) nghỉ hết mùa vì đang chấn thương đầu gối.',
  'Nott.',
  '60.'],
 '/content/drive/MyDrive/Data/L012/L12_V020-Scene-022-02-61080.jpg': ['HD.',
  '18:30:58.',
  'SIÊU THẾ 4?1.',
  '01.',
  '10.',
  'MS.',
  '24.280 đồng/lit.',
  'Xăng RON 95-III.',
  '23.210 đồng/lít.',
  'Xăng E5RON 92.',
  'Dầu diesel.',
  '21.010 đồng/lít.',
  'Dầu lửa.',
  '21260 đồng/lít.',
  'Dầu mazut.',
  '17.090 đồng/kg.',
  'Bà Võ Thị Ánh Xuân, Phó Chủ tịch nước giữ quyền Chủ tịch nước.',
  '60.',
  'Khởi động.',
  '60.'],
 '/content/drive/MyDrive/Data/L012/L12_V020-Scene-152-02-436680.jpg': ['HD.',
  '18:39:10.',
  '60.',
  'Phát hiện hóa thạch cá heo sông 16 triệu năm tuổi tại Peru.',
  '69.',
  'Phương pháp nhịn ăn gián đoạn có.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-003-01-17760.jpg': ['11s 07.',
  '12012024.',
  '8.',
  'Phuonganh.',
  'IDMEDICALCOMPANY.',
  'Inham on.',
  '103155.',
  'GENEAUNCArE.',
  'F1615412401121.',
  'GA-29w5D.',
  'Mi 11',
  '200.',
  '44Hz/101 cm.',
  '8/10.',
  'HD.',
  'TRND 8.20-23.',
  '18:30:14.',
  'CROM.Y.',
  'FFATS.',
  'Radiantma.',
  'Tiếp cận thất bại bằng kim.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-004-01-19440.jpg': ['18:30:16.',
  'THÍNH.',
  'giây.',
  'TP.HCM: EM BÉ THỨ 2 ĐƯỢC THÔNG TIM BÀO THAI.',
  'CHÀO ĐỜI KHỎE MANH.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-002-02-9360.jpg': ['HD.',
  '18:30:05.',
  '1.',
  'VĨNH PHÚ.',
  'THƯ ĐÌNH.',
  'giây.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-006-02-23560.jpg': ['18:30:20.',
  'NGHỀ CHĂM SÓC CÂY XANH TẠI TP.HCM.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-009-01-27800.jpg': ['Sanna.',
  '18:30:24.',
  'SQUARISL.',
  'Malism.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-035-02-141520.jpg': ['VHD.',
  '18:32:24.',
  'MẠC HOÀI THƯƠNG.',
  'giây.',
  'MỆ BỆNH NHI.',
  'Cuộc thi và Triển lãm ảnh nghệ thuật Việt Nam năm 2024.',
  '- Hà Nội: Xử lý nhiều vi phạm an toàn.',
  '60.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-037-02-146960.jpg': ['18:32:29.',
  '69.',
  '60.',
  'Hà Nội: Xử lý nhiều vi phạm an toàn giao thông qua phản ánh của người dân.',
  'DONG TH.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-050-02-199360.jpg': ['HD.',
  '183322.',
  'XANGESTRONORY.',
  'KNORS.',
  'XỈ NGHIệp Bản Lê Xang Dầu.',
  'CỬA HÀNG XĂNG DẦU SỐ 01.',
  'XANG RON OSI.',
  '17',
  'Thay đổi.',
  'Xăng E5/RON92:4 277 đồ.',
  'Quảng Nam.',
  '69.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-090-02-299640.jpg': ['HTV.',
  'Điểm TỪ VĂN GIÓI THIẾU VIẾC LẠI.',
  '18:35:02.',
  'UNPAYFUTAL.',
  'MIEN PHI CHO NGUOI LAO DONG.',
  'TRUOC VÀ SAU TẾT GIÁP THIN 2024.',
  'Mất chi tiết liên hệ.',
  'Trung tâm Dịch vụ việc làm thành phố Hồ Chí Minh.',
  'Địa chỉ: 153 Xô Viết Nghệ Tĩnh, Phường 17',
  'Quân Bình Thanh, TPHCM.',
  'Dòng giới thiêu việc làm - Thi trường lao đông.',
  'Bộ Công Thương ban hành văn bản.',
  '40.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-164-02-520440.jpg': ['18:38:43.'],
 '/content/drive/MyDrive/Data/L010/L10_V001-Scene-180-02-561880.jpg': ['HD.',
  '18:39:24.',
  'TIẾP TO.',
  '2.',
  'giây.',
  'TRIỂN LÃM HOA LAN THƯỜNG NIÊN LẦN THỨ 21'],
 '/content/drive/MyDrive/Data/L010/L10_V026-Scene-008-01-26000.jpg': ['18:30:22.',
  '5.',
  'HIẾT.',
  '.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-069-01-240840.jpg': ['TATSUNO.',
  'HIVS.',
  'HD.',
  'TỔNG SỐ.',
  '06:33:53.',
  'SHG.',
  'TC.',
  '0.',
  'LÍT.',
  '005.',
  '26200.',
  'ĐƠN GIÁ.',
  '26200.',
  '7890.',
  'Zogo.',
  '0562.',
  'ason.',
  'n-z.',
  'PIPERIPIPS.',
  'DEBN.',
  'OZEE.',
  'ocoa.',
  'Melame.',
  'ocga.',
  'XĂNG RON 95.',
  'Kiên Giang: Giám sát truy xuất nguồn gốc hải sản khai thác biển.',
  '69.',
  '00.',
  'Kiên Giang.',
  'h.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-095-02-305320.jpg': ['HD.',
  '06:34:57.',
  '60.',
  'Ngành Đường sắt mở bán vé tàu Huế - Đà Nẵng.',
  'Pacific Airlines tạm.',
  '65.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-090-02-288840.jpg': ['HD.',
  '06:34:41.',
  'Chưa chuyển giao công trình văn hóa, thể thao cho TP.Tuy.',
  '69.',
  'Bình Thuận: Đảo Phú Quý đó!'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-092-02-296880.jpg': ['1.',
  'HD.',
  '06:34:49.',
  '69.',
  'Tập đoàn Dầu khí Việt Nam bổ nhiệm Tổng giám đốc mới.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-103-02-323040.jpg': ['HIVS.',
  '06:35:15.',
  'Bắc Bộ tăng nhiệt trước khi chuyển rét từ 19/3.',
  '60.',
  'Các tỉnh.',
  'Ngưới 10 độ C, trời mưa rét.',
  '60.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-100-02-318400.jpg': ['HIVS.',
  'HD.',
  '06:35:10.',
  'Bắc Bộ tăng nhiệt.',
  'Miền Bắc đón không khí lạnh, có nơi dưới 10 độ C, trời mưa rét.',
  '69.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-113-02-355720.jpg': ['UN.',
  'HD.',
  '06:35:47.',
  'Quận Bình Tân: Thanh.',
  '69.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-150-02-470360.jpg': ['HLV.',
  'HD.',
  '06:40:49.',
  '60.',
  'Tai nạn tại Ghana, ít nhất 21 người tử vong.',
  '69.',
  'Cách giới nghiêm ở thủ đô Port-au-Prince.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-160-02-541400.jpg': ['06:42:00.',
  '65.',
  '69.',
  'Mexico, Canada chỉ trích quy định mới của Mỹ về dán nhân thực phẩm.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-197-02-635720.jpg': ['HIVS.',
  'HD.',
  '06:43:34.',
  'Nhiều.',
  '60.',
  '60.',
  'Bộ Ngoại giao đang đàm phán với 15 nước về miễn thị thực song phương.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-254-02-872720.jpg': ['HIV9.',
  'HD.',
  '06:49:09.',
  'trái phép ở Phú Quốc: Chủ đầu tư tháo dỡ 1/3 công trình.',
  'Ninh Thuận: Giả đò mua trái cây.',
  '10.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-258-01-883440.jpg': ['HD.',
  '06:49:20.',
  'Quảng Ngãi: Chở đường lậu, tài xế bị xử phạt gần nửa tỉ đồng.',
  '60.'],
 '/content/drive/MyDrive/Data/L011/L11_V018-Scene-265-02-925120.jpg': ['HIV.',
  '06:50:02.',
  'TÁC PHẨM MỚI CỦA BANKSY XUẤT HIỆN Ở LUÂN ĐÔN.',
  'Khai mạc Triển lãm tranh truyện Hà.',
  '60.']}

In [158]:
import pandas as pd
data = []
# Giả sử biến của bạn tên là `data_dict`
for idx, (img_path, text_list) in enumerate(data_dict.items()):
    merged_text = ' '.join(text_list)  # Hoặc '\n'.join() nếu muốn xuống dòng
    data.append({ 'image_path': img_path, 'full_content': merged_text})

df = pd.DataFrame(data)

In [159]:
# df = pd.read_excel('data/data/review_full_text_vnmese_100.xlsx')

In [160]:
df.head()

,image_path,full_content
0,/content/drive/MyDrive/Data/L012/L12_V001-Scen...,"HTV. 18:30:13. Ảnh: VIỆT NAM, QUANG VINH, MUỐN..."
1,/content/drive/MyDrive/Data/L012/L12_V001-Scen...,"ITIV. HD. 1830:18. HAT. ""Xét XỬỤ CỤ CÂM PHẠM Đ..."
2,/content/drive/MyDrive/Data/L012/L12_V001-Scen...,18:30:28. TAI NẠN LIÊN HOÀN TRÊN CAO TỐC VĨNH ...
3,/content/drive/MyDrive/Data/L012/L12_V001-Scen...,"HD. 18:30:20. THÍNH. giây. ""Xét XỬ VU ""(XÂM PH..."
4,/content/drive/MyDrive/Data/L012/L12_V001-Scen...,VHD. 18:31:01. TP.HCM: RA QUÂN HUẤN LUYỆN NĂM ...

In [161]:
df.tail()

,image_path,full_content
38,/content/drive/MyDrive/Data/L011/L11_V018-Scen...,"06:42:00. 65. 69. Mexico, Canada chỉ trích quy..."
39,/content/drive/MyDrive/Data/L011/L11_V018-Scen...,HIVS. HD. 06:43:34. Nhiều. 60. 60. Bộ Ngoại gi...
40,/content/drive/MyDrive/Data/L011/L11_V018-Scen...,HIV9. HD. 06:49:09. trái phép ở Phú Quốc: Chủ ...
41,/content/drive/MyDrive/Data/L011/L11_V018-Scen...,"HD. 06:49:20. Quảng Ngãi: Chở đường lậu, tài x..."
42,/content/drive/MyDrive/Data/L011/L11_V018-Scen...,HIV. 06:50:02. TÁC PHẨM MỚI CỦA BANKSY XUẤT HI...

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   image_path    43 non-null     object
 1   full_content  43 non-null     object
dtypes: object(2)
memory usage: 816.0+ bytes

### Preprocessing

#### lower case

In [163]:
df['clean_text'] = df.full_content.str.lower()

#### check dup

In [164]:
# df.duplicated(subset=['clean_text', 'rating_New']).any()

#### check missing values

In [165]:
#If missing values, drop else next!

#### Replace multiple dots

In [166]:
df.clean_text = df.clean_text.str.replace('\.+', '.', regex=True)

#### Clean data

In [167]:
_processor = TextProcessor()

In [168]:
df.clean_text = df.clean_text.apply(lambda x: _processor.process_text(x))
df.clean_text.head()

0    htv. 18:30:13. ảnh: việt nam, quang vinh, muốn...
1    itiv. hd. 1830:18. hat. "xét xửụ cụ câm phạm đ...
2    18:30:28. tai nạn liên hoàn trên cao tốc vĩnh ...
3    hd. 18:30:20. thính. giây. "xét xử vu "(xâm ph...
4    vhd. 18:31:01. tp.hcm: ra quân huấn luyện năm ...
Name: clean_text, dtype: object

In [169]:
df.clean_text = df.clean_text.apply(lambda x: _processor.covert_unicode(x))
df['clean_text'].head(5)

0    htv. 18:30:13. ảnh: việt nam, quang vinh, muốn...
1    itiv. hd. 1830:18. hat. "xét xửụ cụ câm phạm đ...
2    18:30:28. tai nạn liên hoàn trên cao tốc vĩnh ...
3    hd. 18:30:20. thính. giây. "xét xử vu "(xâm ph...
4    vhd. 18:31:01. tp.hcm: ra quân huấn luyện năm ...
Name: clean_text, dtype: object

In [170]:
# df.clean_text = df.clean_text.apply(lambda x: _processor.process_postag_thesea(x))
# df['clean_text'].head(5)

In [171]:
df.clean_text = df.clean_text.apply(lambda x: _processor.remove_stopword(x))
df['clean_text'].head(5)

0    htv. 18:30:13. ảnh: việt nam, quang vinh, nam....
1    itiv. hd. 1830:18. hat. "xét xửụ cụ câm phạm đ...
2    18:30:28. tai nạn liên hoàn tốc vĩnh hảo - pha...
3    hd. 18:30:20. thính. giây. "xét xử vu "(xâm ph...
4    vhd. 18:31:01. tp.hcm: quân huấn luyện 2024. g...
Name: clean_text, dtype: object

In [172]:
df.clean_text.dropna(inplace=True)
df = df[df.clean_text != ''].reset_index(drop=True)
df.clean_text.head()

0    htv. 18:30:13. ảnh: việt nam, quang vinh, nam....
1    itiv. hd. 1830:18. hat. "xét xửụ cụ câm phạm đ...
2    18:30:28. tai nạn liên hoàn tốc vĩnh hảo - pha...
3    hd. 18:30:20. thính. giây. "xét xử vu "(xâm ph...
4    vhd. 18:31:01. tp.hcm: quân huấn luyện 2024. g...
Name: clean_text, dtype: object

In [186]:
df.loc[8,'clean_text']

'thể thao. nội dung thông báo chí. 18:34:05. năm, thông phản ánh báo chí cụm rạp phổ biến phim. "mai"), khâu kiếm soát vé lỏng lẻo, lọt khán giả 18 mua vé. phim; 21 02 2024, tra văn hóa, thể thao du lịch có. công văn 14/tt-vhgđ gửi tra sở văn hóa, thể thao du lịch; sở. văn hóa thể thao cường tra, kiểm tra chấp hành quy định. pháp luật điện ảnh rạp chiếu phim; thực hiện chi đạo tra bộ, tra sở văn hóa thể thao công. văn 39/tts 21 02 2024 cường kiểm tra xử lý hành vi vi. vi phạm quy định pháp luật phổ biến phim địa bàn thành phố hồ chí minh gửi. phòng văn hóa thông thành phố thủ đức 21 quận, huyện đề nghị. phòng văn hóa thông thành phố thủ đức 21 quận, huyện phối hợp các. tổ chức, cá nhân hoạt động kinh doanh lĩnh vực điện ảnh, sở hoạt động kinh doanh,. phỏ biến nhiều. vi phạm nồng độ cồn lái xe máy tai nạn chết người. %. đồng tháp: chìm ghe chở đất, một.'

In [174]:
# from processor.text import TextProcessor

# _processor = TextProcessor()
# print(dir(_processor))

### Feature engineering

In [175]:
df.rating_New.value_counts()

AttributeError: 'DataFrame' object has no attribute 'rating_New'

In [ ]:
df['label'] = df.rating_New.apply(lambda x: 1 if x>=4 else 0)

In [ ]:
df.label.value_counts()

1    87
0    13
Name: label, dtype: int64

#### Vectorize

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
vectorized_data = vectorizer.fit_transform(df.clean_text)

In [ ]:
df_vectorized = pd.DataFrame(vectorized_data, columns=vectorizer.get_feature_names_out())

ValueError: Shape of passed values is (100, 1), indices imply (100, 582)

### Build models

#### split into train/test

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df_vectorized.drop('label', axis = 1)
y = df_vectorized[['label']]

NameError: name 'df_vectorized' is not defined